[package]
name = "ctv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4.19"
filetime = "0.2.14"
humansize = "1.1.1"
libc = "0.2.95"
pretty-bytes = "0.2.2"
structopt = "0.3.21"
termion = "1.5.6"
users = "0.11.0"
