# Default ctv config.toml

file_size_position      = "1"
file_owner_position     = "2"
file_perms_position     = "3"
file_time_position      = "4"
file_extension_position = "-1"
dir_name_color          = "BLUE"
file_name_color         = "LIGHTRED"
file_time_color         = "LIGHTCYAN"
file_size_color         = "BLUE"
file_owner_color        = "LIGHTMAGENTA"
file_perms_color        = "BLUE"
file_extension_color    = "YELLOW"
dir_name_style          = "NORMAL"
file_name_style         = "NORMAL"
file_time_style         = "BOLD"
file_size_style         = "BOLD"
file_owner_style        = "NORMAL"
file_perms_style        = "BOLD"
file_extension_style    = "ITALIC"
file_time_format        = "%m-%d-%Y::%H:%M:%S"
file_time_type          = "CREATED"
tree_layer_limit        = "3"
show_file_metadata      = "TRUE"
show_dir_metadata       = "TRUE"
pipe                    = "│"
elbow                   = "└──"
tee                     = "├──"
pipe_prefix             = "│"
space_prefix            = " "
dir_color               = "BLUE"
symlink_color           = "LIGHTMAGENTA"
path_color              = "WHITE"
pipe_color              = "YELLOW"
chard_color             = "YELLOW"
blockd_color            = "LIGHTGREEN"
socket_color            = "LIGHTRED"
read_color              = "LIGHTGREEN"
write_color             = "LIGHTRED"
execute_color           = "LIGHTGREEN"
dash_color              = "LIGHTBLACK"
spacing                 = "0"
show_short              = "false"

# Available Colors
  # BLACK, BLUE, CYAN, GREEN, MAGENTA, RED, WHITE, YELLOW,
  # LIGHTBLACK, LIGHTBLUE, LIGHTCYAN, LIGHTGREEN, LIGHTMAGENTA,
  # LIGHTRED, LIGHTWHITE, LIGHTYELLOW


# Available Font Styles
  # BOLD, DIMMED, ITALIC, UNDERLINE, BLINK,
  # REVERSE, HIDDEN, STRICKEN, NORMAL
